name: Daily Time Logger

on:
  schedule:
    # Runs at 00:00 UTC daily
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-logger:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Run logging script
        run: python main.py
        
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add log.txt
          # Only commit and push if there are changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update log with timestamp" && git push)
